### ISSUE TITLE
I'm so glad that BoofCV also has a python wrapper!

### ISSUE THREAD

**Issue by ivanquirino** [lessthanoptimal/PyBoof#1]
Really, I'm about to use a python deep learning framework (fast.ai wrapper over PyTorch), and I'll have to do QRCode detection, crop and rotate on images before piping those images to pytorch. I already use qrcode detection from BoofCV in java (top of class implementation), so this fits like a glove! Thanks!

**Comment by lessthanoptimal** [comment]
Thanks for letting me know you find it useful! If I know its being used I'm more likely to provide more frequent updates. I should probably add more features so that it's more useful...
