### ISSUE TITLE
PyBoof concurrency issue

### ISSUE THREAD

**Issue by lfferreira** [lessthanoptimal/PyBoof#10]
Hi,

I’m having difficulties in running PyBoof concurrently in multiple processes (it’s a Flask application running in GUNICORN).
Would it be possible for you to help me?
Keep getting the following exception when several worker processes are created (all is well in single process with GEVENT):

Launching Java process
Gateway Server Started
Exception in thread "main" py4j.Py4JNetworkException
              at py4j.GatewayServer.startSocket(GatewayServer.java:788)
              at py4j.GatewayServer.start(GatewayServer.java:763)
              at py4j.GatewayServer.start(GatewayServer.java:746)
              at pyboof.PyBoofEntryPoint.main(PyBoofEntryPoint.java:59)
Caused by: java.net.BindException: Address already in use (Bind failed)
              at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
              at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
              at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
              at py4j.GatewayServer.startSocket(GatewayServer.java:786)
              ... 3 more

I guess it’s trying to open the same port on all processes.

Is this a disabling issue? Should I assign different ports on every process? How would I do it as PyBoof doesn’t seem to have a way to choose a Port?

Thanks in advance for any help you may provide.

Luís Ferreira

**Comment by lessthanoptimal** [comment]
I might need to add this functionality back into the library. Before I start coding, I would like to double check that I understand your use case.  Is the following true:

1) You have more than one process (not a thread) that is calling PyBoof
2) You wish to have those running at the same time completely independently
3) Launching multiple JVM instances is just fine

**Comment by lfferreira** [comment]
Hi, thanks for replying.

Yes, that is what I would need.
Was there a version that supported this?
Ir you make this change when do you think this could be available?
I have a deadline this week that may force me to use another library.

Best regards,

Luís Ferreira

A segunda, 11/10/2021, 22:44, Peter Abeles ***@***.***>
escreveu:

**Comment by lessthanoptimal** [comment]
If I remember correctly, you need to specify a port for Py4J to connect to and if it can't find a JVM with that port open it spawns a new JVM. Very early versions required you to call a function to initialize and specify a port. Odds are that version is lacking whatever feature you are using. I've started updating it for BoofCV 0.39 and my goal is to get this new feature in there this week, but that depends on how efficient I am. This seems like a feature people will need so I'll keep it high priority.

Out of curiosity, what are you using PyBoof for?

**Comment by lfferreira** [comment]
Thank you very much for giving priority to this. I'm sure there are many more who will benefit from this improvement. I'll be happy to use it and test it on my server application as soon as you create a new deployment.
I'm currently using it for QR-Code detection in a set of images that are being sent for a server. It seems to be the best library for that purpose. It's possible I'll be using it for other purposes in the server also.

Please keep me posted.

**Comment by lfferreira** [comment]
Hi again,

How are things doing with this new update? When would you like me to test it?
Looking forward to hear for news.

Luís Ferreira

**Comment by lessthanoptimal** [comment]
Try the latest code in SNAPSHOT branch now. Just did a quick test and it passed. There's an example which shows you how launch multiple instances. Let me know if that example does a good job explaining.

**Comment by lfferreira** [comment]
Thanks, let me check on it...

**Comment by lfferreira** [comment]
Should I "pip uninstall pyboof" and then follow the general install instructions but for SNAPSHOT branch?

**Comment by lessthanoptimal** [comment]
It should overwrite the old install. Does it fail if you don't uninstall?

**Comment by lfferreira** [comment]
I'm seeing the code and I think I have a problem. My server (GUNICORN) instantiates several processes at once and there's no way for me to make processes to wait for each other. Because you use an environment variable to hold the port, even if there's a "sleep(20)", all processes will start and wait, and probably the last one that sets the PORT will be the port that will be used by all...

I know it probably isn't easy but is there a way to pass the PORT directly without using environment variables? Otherwise I will have to put an incremental sleep on all processes so that they will awake at different times, but if a process restarts there is still a probability of a wrong PORT

You could for instance define a PORT interval like [FROM..TO] and send it to the JVM and then return the usable PORT in the process startup call (don't know if it makes sense)

**Comment by lessthanoptimal** [comment]
I'm not familiar with GUNICORN, but just to double check it's spawning processes and not threads right? Could you pass in the ports as an argument then programically set the environmental variable like it does in this [example](https://github.com/lessthanoptimal/PyBoof/blob/SNAPSHOT/examples/launch_multiple_jvm.py)?

I did look into an alternative strategy where it didn't automatically launch the JVM and instead required you to call an initialization function. The problem with that is some submodules assume Py4J has been setup and make calls to it. That can be done, but would require some code changes that are more involved.

**Comment by lfferreira** [comment]
> I'm not familiar with GUNICORN, but just to double check it's spawning processes and not threads right? Could you pass in the ports as an argument then programically set the environmental variable like it does in this [example](https://github.com/lessthanoptimal/PyBoof/blob/SNAPSHOT/examples/launch_multiple_jvm.py)?

lfferreira > I can try to figure out something like that (I had seen that example) but I have to make sure that initialization is done separately in the processes maybe with some sort of lock or semaphores otherwise 2 different processes that use different ports will use the same port as the last that sets the _PORT variables will serve those same variables to both JVMs. 

> I did look into an alternative strategy where it didn't automatically launch the JVM and instead required you to call an initialization function. The problem with that is some submodules assume Py4J has been setup and make calls to it. That can be done, but would require some code changes that are more involved.

lfferreira > if you could have some Initialization function to be executed after the "import pyboof", you could LOCK that initialization and make it "process safe" - ex: pb.init(python_port, jvm_port) would LOCK between processes (only one process at a time woul execute it while the others waiting)

For now I will see if I can LOCK the initializtion process in my code. Thanks for your effort so far, this should be better than the current alternative

**Comment by lessthanoptimal** [comment]
If they are completely separate processes shouldn't the environmental variables be local? They would be copied from the shell which forked the process and after that they will be decoupled, right? I think this is where the disconnect is in our thoughts.

**Comment by lfferreira** [comment]
I had an error on "pb.init_memmap()". It worked without it. Is it not supported/needed now?

**Comment by lfferreira** [comment]
I managed to make the new version work in my code through the following initialization code in the processes (I use a file lock mechanism to access/write a file that manages the process pid allocated to every used port):

```
import os
import json
from filelock import FileLock


# DEFINITIONS

# Ports to be used

FROM_PORT = 24000
MAX_PORTS = 16 * 2


# Help files location

USED_PORTS_FILE = 'pyboof.ports.txt'
USED_PORTS_LOCK = 'pyboof.ports.lock'

WIN_PATH = '/'
LINUX_PATH = '/home/ubuntu'

if os.name == 'nt':
    os_path = WIN_PATH
else:
    os_path = LINUX_PATH
ports_path = os.path.join(os_path, USED_PORTS_FILE)
lock_path = os.path.join(os_path, USED_PORTS_LOCK)


# FUNCTIONS

# Sending signal 0 to a pid will raise an OSError exception
# if the pid is not running, and do nothing otherwise.
def check_pid(pid):        
    """ Check For the existence of a unix pid. """
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    else:
        return True


# START

# Start by ensuring there's a lock file and lock entry

if not os.path.isfile(lock_path):
    with open(lock_path, 'w') as f: pass

lock = FileLock(lock_path, timeout=10)

with lock:

    # Get current status

    if not os.path.isfile(ports_path):
        with open(ports_path, 'w') as f:
            f.write('{}')

    with open(ports_path, "r") as f:
        port_pids = json.loads(f.read())
    

    # Check free ports

    for pb_port in range(FROM_PORT, FROM_PORT + MAX_PORTS, 2):
        port_pid = port_pids.get(str(pb_port))

        if not port_pid or not check_pid(port_pid): break


    # Save usage

    port_pids[str(pb_port)] = os.getpid()

    with open(ports_path, "w") as f:
        f.write(json.dumps(port_pids)) 


    # Start PyBoof on given port

    os.environ['PYBOOF_JAVA_PORT'] = str(pb_port)
    os.environ['PYBOOF_PYTHON_PORT'] = str(pb_port + 1)

    import pyboof as pb
```

I also noticed that your changes still didn't correct the following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by py4j.reflection.MethodInvoker$1 (file:/home/ubuntu/UnifAI/covitest2/venv/lib/python3.8/site-packages/PyBoof-0.39.1.post1-py3.8.egg/pyboof/PyBoof-all.jar) to method java.util.ArrayList$Itr.next()
WARNING: Please consider reporting this to the maintainers of py4j.reflection.MethodInvoker$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by lessthanoptimal** [comment]
> I had an error on "pb.init_memmap()". It worked without it. Is it not supported/needed now?

It got renamed and is automatically called now.

**Comment by lessthanoptimal** [comment]
Great that you got it working! Although it does seem a bit cumbersome to require locks. I guess that's because you don't have a central authority specifying the ports and you have to look to see what's in use. Would be nice if the library could handle that mess. I'll save that for another day!

Those error messages can be ignore for now. It's the JVM warning that you're doing something that will break a future JVM release.

**Comment by lessthanoptimal** [comment]
Think this is good enough for now and 0.39.1 can be released to pypi?

**Comment by lfferreira** [comment]
Yes, now it's working fine by me. As you said, I use that Filelock mechanism because I can't distinguish one process from the other (GUNICORN just launches N workers and there's no specific config by worker process). In the future it would be nice to "handle that mess".
Thank you so much for this new release. I've allready integrated it in my server. Hope someone else also benefits from this.

Nice talking to you. I'm closing this issue if you don't mind...

Luís Ferreira
