### ISSUE TITLE
Java 17 breaking PyBoof

### ISSUE THREAD

**Issue by j3r3mias** [lessthanoptimal/PyBoof#14]
Hi, I installed and tested PyBoof two times, one using pip and then other using the source (SNAPSHOT) to test qr-code and micro-qr-codes detection, but none of them worked. After the installation I ran [microqr_detect.py](https://github.com/lessthanoptimal/PyBoof/blob/SNAPSHOT/examples/microqr_detect.py) and [qrcode_detect.py](https://github.com/lessthanoptimal/PyBoof/blob/SNAPSHOT/examples/qrcode_detect.py) that returned zero detections using all the images provided in [data @ 526f3a9](https://github.com/lessthanoptimal/BoofCV-Data/tree/526f3a90399040ec35b209a973681882043d2cc1).

I'm using python 3.8.10 and open-jdk 17.0.3.

**Comment by lessthanoptimal** [comment]
thanks. Just verified it. A lot of other stuff is messed up also. I'm a little perplexed what went wrong as everything gets tested carefully before a release.

**Comment by lessthanoptimal** [comment]
something external to the PyBoof code base is now horribly broken. Java fields can no longer be accessed and lists are returned as empty. Most of the examples no longer work. Updating Py4j didn't fix it.

**Comment by lessthanoptimal** [comment]
This appears to be an issue with Java 17. Everything worked when I reverted to Java 15. Most likely caused by more restrictions. I'll work on this more when I have a chance.

**Comment by dogadogan** [comment]
I have the same issue. QR code detector returns nothing for Java 17. Does anyone have a solution to this?

**Comment by lessthanoptimal** [comment]
Might be stuck until Py4J resolves this problem:

https://github.com/py4j/py4j/issues/485

ETA on the fix is end of July 2022

**Comment by lessthanoptimal** [comment]
@dogadogan Only fix I know is to revert to an older version of Java. I tried disabling some of the new security features in Java and that didn't fix it. Seems to be a more low level issue with Py4J and based on the comments there's no trivial fix.

**Comment by lessthanoptimal** [comment]
Updated Py4J and Java 17 is no longer an issue
