### ISSUE TITLE
Not able to read all QRs from same image

### ISSUE THREAD

**Issue by phohtoo** [lessthanoptimal/PyBoof#15]
Hi

I am encountering a case that, not all QRs in the image is detected by PyBoof. 

I have also attached sample QR image for testing and wondering if there is anything we can configure with existing PyBoof version? Or it is something BoofCV model need to be improved? Thanks

Linn Htoo

![QRSample](https://user-images.githubusercontent.com/450242/171116199-94fc0e93-b9b5-4c39-b7b7-89416750e62c.jpg)

**Comment by phohtoo** [comment]
I am wondering if I can get some help for this issue. thanks

**Comment by lessthanoptimal** [comment]
![image](https://user-images.githubusercontent.com/739159/175222450-2063266c-7b80-41ae-b549-e62d050e59a7.png)

Sorry, thought I had replied. That's an image from the debugging demo app. For some reason it's linking locator patterns together in a really weird way for the bottom QR. This does look like a bug.

**Comment by lessthanoptimal** [comment]
Fix is being tested in Java. So far no regressions found.

**Comment by phohtoo** [comment]
@lessthanoptimal , will new version be released with fix? I tested recompiling PyBoof from source but still having issue. Am I missing anything?

**Comment by lessthanoptimal** [comment]
The python source code now references the latest developmental version of BoofCV. The PyBoof version has been incremented too. So pull and try building from source again and see if it's fixed. As a bonus Aztec Codes are now available in Python.

**Comment by phohtoo** [comment]
@lessthanoptimal , thanks for fixing the issue and i have tested. It works! May I know when new version will be released to PyPI? Thanks again

**Comment by lessthanoptimal** [comment]
It's being blocked right now on finishing a new multi camera calibration implementation. Maybe in a month if everything goes well?

**Comment by lessthanoptimal** [comment]
New release is out!
