### ISSUE TITLE
AttributeError: module 'mmap' has no attribute 'MAP_SHARED'

### ISSUE THREAD

**Issue by GokulNC** [lessthanoptimal/PyBoof#6]
I get that error on running `pb.init_memmap()`.
BTW, I am on Windows.

**Comment by GokulNC** [comment]
Solution:
If the OS is Windows, replace the following line
```
mmap_file = mmap.mmap(mmap_fid.fileno(), length=0)
```
here:
https://github.com/lessthanoptimal/PyBoof/blob/be6fec7/pyboof/__init__.py#L147

Reason:
Different `mmap` APIs for different OS:
https://docs.python.org/3/library/mmap.html#mmap.mmap

**Comment by lessthanoptimal** [comment]
Thanks for pointing this out and telling me up to fix it! This also lead to me running Python on windows for the first time to test it.
