### ISSUE TITLE
LinkageError occurred while loading main class pyboof.PyBoofEntryPoint

### ISSUE THREAD

**Issue by multekedir** [lessthanoptimal/PyBoof#9]
I'm getting this error when I'm trying to run the example. I'm also getting this 

File "/home/muletezemkedir/.local/share/virtualenvs/pyboof-6ZbX4iA_/lib/python3.7/site-packages/pyboof/__init__.py", line 48, in check_jvm
    print("  build dates = {:s} {:s}".format(build_date,java_build_date))
TypeError: unsupported format string passed to NoneType.__format__

LinkageError occurred while loading main class pyboof.PyBoofEntryPoint 	java.lang.UnsupportedClassVersionError: pyboof/PyBoofEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by Ru-Van** [comment]
the same error - Ubuntu 18

**Comment by lessthanoptimal** [comment]
Sorry for taking a bit to fix this. It was accidentally built with a very new version of Java. The build script has been modified to always generate older byte code so this should no longer be an issue.  See v0.37.1
